# mode flags
MODE_MASK: false
MODE_FPN: true

# dataset
DATA:
  BASEDIR: "xxx"
  TRAIN: ["train2017"]
  VAL: "val2017"
  NUM_CATEGORY: 80
  NUM_CLASS: 81
  CLASS_NAMES: []

# basemodel
BACKBONE:
  WEIGHTS: ""  # path/to/weights
  RESNET_NUM_BLOCKS: [3, 4, 6, 3] # for resnet50
  # RESNET_NUM_BLOCKS: [3, 4, 23, 3]
  NORM: "GN"
  STRIDE_1X1: false

# schedule
TRAIN:
  NUM_GPUS: ~
  WEIGHT_DECAY: 0.0001
  BASE_LR: 0.01
  WARMUP: 1000
  STEPS_PER_EPOCH: 500
  STARTING_EPOCH: 1
  LR_SCHEDULE: [200000, 1000000, 1200000, 14000000]
  EVAL_PERIOD: 25

# preprocessing
PREPROC:
  TRAIN_SHORT_EDGE_SIZE: [800, 800]
  TEST_SHORT_EDGE_SIZE: 800
  MAX_SIZE: 1333
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]

# anchors
RPN:
  ANCHOR_STRIDE: 16
  ANCHOR_SIZES: [32, 64, 128, 256, 512]
  ANCHOR_RATIOS: [0.5, 1., 2.]
  POSITIVE_ANCHOR_THRESH: 0.7
  NEGATIVE_ANCHOR_THRESH: 0.3
  FG_RATIO: 0.5 # fg ratio among selected RPN anchors
  BATCH_PER_IM: 256 # total (across FPN levels) number of anchors that are marked valid
  PROPOSAL_NMS_THRESH: 0.7
  HEAD_DIM: 1024
  TRAIN_PRE_NMS_TOPK: 12000
  TRAIN_POST_NMS_TOPK: 2000
  TEST_PRE_NMS_TOPK: 6000
  TEST_POST_NMS_TOPK: 1000  # if you encounter OOM in inference, set this to a smaller number
  # for FPN, #proposals per-level and #proposals after merging are (for now) the same
  # if FPN.PROPOSAL_MODE = 'Joint', these options have no effect
  TRAIN_PER_LEVEL_NMS_TOPK: 2000
  TEST_PER_LEVEL_NMS_TOPK: 1000
  CROWD_OVERLAP_THRESH: 9.99
  NUM_ANCHOR: 15
  MIN_SIZE: 0

# fastrcnn training
FRCNN:
  BATCH_PER_IM: 512  # original is 512, now is 64 for training
  BBOX_REG_WEIGHTS: [10, 10, 5, 5]
  FG_THRESH: 0.5
  FG_RATIO: 0.25

# FPN
FPN:
  ANCHOR_STRIDES: [4, 8, 16, 32, 64]
  RESOLUTION_REQUIREMENT: 32
  PROPOSAL_MODE: "Level"
  NUM_CHANNEL: 256
  NORM: "GN"
  FRCNN_HEAD_FUNC: "fastrcnn_2fc_head"
  FRCNN_CONV_HEAD_DIM: 256
  FRCNN_FC_HEAD_DIM: 1024
  MRCNN_HEAD_FUNC: "maskrcnn_up4conv_head"
  CASCADE: true

# Mask-RCNN
MRCNN:
  HEAD_DIM: 256

# Cascade-RCNN, only avaliable in FPN mode
CASCADE:
  IOUS: [0.5, 0.6, 0.7]
  BBOX_REG_WEIGHTS: [[10, 10, 5, 5], [20, 20, 10, 10], [30, 30, 15, 15]]

# testing
TEST:
  FRCNN_NMS_THRESH: 0.5
  RESULT_SCORE_THRESH: 0.5
  RESULT_SCORE_THRESH_VIS: 0.3
  RESULT_PER_IM: 100

# Smaller threshold value gives significantly better mAP. But we use 0.05 for consistency with Detectron.
